### ISSUE TITLE
Seq2Seq Features?

### ISSUE THREAD

**Issue by MatthewWaller** [KevinCoble/SwiftNNTrainer#1]
First off, this is amazing!!

It’s incredible how much work you’ve put into this application. 

Do you foresee layers like RNN and LSTM, or even Transformer models in the future? I would love to be able to train seq2seq models with Metal acceleration.

**Comment by KevinCoble** [comment]
Thank you for the comment.  As it has not seen the popularity of my AIToolbox framework, I was wondering if anyone had seen it.  Spread the word if you can...

Yes, I would like to get recursive layers in the mix, but currently Apple doesn't support them in the Metal Performance Shaders framework - the basis of the program.  I am waiting to see what changes are announced, if any, next week at WWDC.  MLModel does support those types of layers, so I hope the two frameworks become more feature-parity this year.  If not I'll have to look into custom shaders - possible but fairly difficult to integrate with Apples MPS.

I am currently working on adding a fourth tab to the application - Hyperparameter Tuning.  It's now summer, so my coding schedule is a little slower, but look for it soon.
